# Generated by Django 4.0.4 on 2022-08-02 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='images')),
                ('posted_on', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('posted_by', models.CharField(max_length=20)),
                ('post_id', models.CharField(max_length=10)),
            ],
        ),
    ]
