# Generated by Django 4.0.6 on 2022-07-31 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('heading', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('post_id', models.IntegerField()),
                ('posted_by', models.CharField(max_length=20)),
                ('posted_on', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('upi_id', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
