# Generated by Django 4.0.6 on 2022-07-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='post_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
