# Generated by Django 4.0.6 on 2022-08-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpostmodel',
            name='upi_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
