# Generated by Django 4.0.6 on 2022-08-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_newpostmodel_upi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpostmodel',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
