# Generated by Django 4.0.6 on 2022-08-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_newpostmodel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpostmodel',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='newpostmodel',
            name='post_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='newpostmodel',
            name='posted_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='newpostmodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newpostmodel',
            name='upi_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
