# Generated by Django 4.0.6 on 2022-08-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_newpostmodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpostmodel',
            name='qr_code',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
